server {
    listen 443 ssl;
    server_name emdr-express.kz;

    ssl_certificate /var/www/html/ssl/cert.pem;
    ssl_certificate_key /var/www/html/ssl/privkey.pem;

    root /var/www/html/public;

    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        root /var/www/html;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

}
